### ISSUE TITLE
Inherited property values: Hash.FromAnonymousObject

### ISSUE THREAD

**Issue by pk-picturepark** [dotliquid/dotliquid#221] opened 2017-01-12 11:02 UTC
Hi, 

Up until dotliquid version 2.0.30 the method Hash.FromAnonymousObject could process property values of inherited classes.

Sample:

```
public class BaseTestClass
{
  public string Name { get; set; }
}

public class TestClass : BaseTestClass
{}
```

When passing an instance of TestClass into Hash.FromAnonymousObject, the property "Name" is now omitted.

I couldn't find any changelog info since version 1.8.0. So is this a new restriction or a bug to be resolved?

Thanks

**Comment by albertospelta** [comment] 2017-02-15 14:25
You should find this message in your template `Errors` collection:

> Object 'TestClass' is invalid because it is neither a built-in type nor implements ILiquidizable

As you can read [here](https://github.com/dotliquid/dotliquid/wiki/DotLiquid-Drops ), types of parameters are now limited to .NET primitive types and some collection types.
So, in order to support arbitrary types, you should inherit from `Drop` class.

``` c#
public class BaseTestClass : Drop
{
    public string Name { get; set; }
}

public class TestClass : BaseTestClass
{
}

class Program
{
    static void Main(string[] args)
    {
        var template = Template.Parse(@"Hello {{ user.Name }} !");
	var variable = Hash.FromAnonymousObject(new
	{
		user = new TestClass()
		{
			Name = "Alberto"
		}
	});

	var result = template.Render(variable);
	template.Errors.ForEach(Console.WriteLine);
	Console.WriteLine(result);

	Console.ReadKey();
    }
}
```

**Comment by TigerPoint** [comment] 2021-05-11 09:39
If you have multi-level inheritance then I suggest converting your object to a `Dictionary` then using `Hash.FromDictionary` instead

**Comment by microalps** [comment] 2021-07-26 03:45
I am unable to reproduce any of the above in a current version. @TigerPoint do you have a test case? This might have been fixed in the latest build as @robin-parker changed the behavior of nested dictionaries.

**Comment by microalps** [comment] 2021-09-01 09:35
Closing as we haven't heard back from the user.

**Closed by microalps** 2021-09-01 09:35 UTC
Labels: needs response
