### ISSUE TITLE
Flatten() in sort() while using IEnumerable<IDictionary>

### ISSUE THREAD

**Issue by rarayudu** [dotliquid/dotliquid#289] opened 2017-12-13 04:37 UTC
In the StandardFilter.cs the sort() method is doing Flatten() on each item if the given input is of type IEnumerable.

Any reason why we are doing this? This is causing issues when trying to sort a list of dictionary objects based on a property as each dictionary item in the list is flattened. And because of this the specific if case which we have later for IDictionary type objects won't hit.

Can we not do flattening for the type IDictionary list, similar to what we are doing for type hash list.

**Comment by microalps** [comment] 2021-04-14 01:59
Valid Q - But closing as it is a duplicate of #228. More info in the related issue.

**Closed by microalps** 2021-04-14 01:59 UTC
