### ISSUE TITLE
Integration between dotliquid and with .NET Core

### ISSUE THREAD

**Issue by jindovu** [dotliquid/dotliquid#185] opened 2016-06-12 06:27 UTC
Hello everyone,
      Now .NET upgrade .NET Core RC2 run on Linux, Window OS, I build a system using dotLiquid to generate template site, please let me know how can I integration between dotLiquid and .NET Core RC2

Thank you so much.

**Comment by haf** [comment] 2016-07-22 15:57
Yes, we'd love a PR making that possible!

**Comment by haf** [comment] 2016-07-22 15:58
Duplicate of #181

**Closed by haf** 2016-07-22 15:58 UTC
Labels: feature
